# coding=UTF-8
from __future__ import unicode_literals

from bpmn import conditions, handlers
from bpmn.models import Process, Task

# 基础发货流程
BASE_DELIVERY = {
    Process.START_TASK: 'init_order',
    Process.END_TASK_LIST: ['mark_received', 'close_order'],
    'init_order': {
        'name_cn': '新增订单',
        'note': '采购方提交订单后，系统自动生成发货流程',
        'transit_type': Task.AUTO_TRANSIT,
        'condition_list': [],
        'run': None,
        'mutex': [],
        'target_list': ['mark_order_paid', 'apply_change_price', 'mark_order_reviewing', 'mark_order_refunding', 'close_order'],
    },
    'mark_order_paid': {
        'name_cn': '标记付款',
        'note': '订单支付后，标记付款',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_can_pay],
        'run': handlers.mark_order_paid,
        'mutex': [],
        'target_list': ['mark_order_picking'],
    },
    'apply_change_price': {
        'name_cn': '申请改价',
        'note': '订单支付前，申请改价',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_can_change_price],
        'run': handlers.order_apply_change_price,
        'mutex': [],
        'target_list': ['change_price_valid', 'change_price_invalid'],
    },
    'change_price_valid': {
        'name_cn': '改价通过',
        'note': '订单改价审核通过',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_is_changing_price],
        'run': handlers.order_change_price_valid,
        'mutex': [],
        'target_list': ['mark_order_paid'],
    },
    'change_price_invalid': {
        'name_cn': '改价不通过',
        'note': '订单改价审核不通过',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_is_changing_price],
        'run': handlers.order_change_price_invalid,
        'mutex': [],
        'target_list': ['mark_order_paid'],
    },
    'mark_order_reviewing': {
        'name_cn': '订单待审核',
        'note': '订单支付后，开始审核订单',
        'transit_type': Task.AUTO_TRANSIT,
        'condition_list': [],
        'run': handlers.mark_order_reviewing,
        'mutex': [],
        'target_list': ['mark_order_valid', 'mark_order_invalid'],
    },
    'mark_order_refunding': {
        'name_cn': '标记退款',
        'note': '订单支付后，因某种原因发起退款',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_can_refund],
        'run': handlers.mark_order_refunding,
        'mutex': [],
        'target_list': ['close_order'],
    },
    'mark_order_valid': {
        'name_cn': '订单审核通过',
        'note': '审核完订单清单中的药品资质，并全部通过后，点击【审核通过】',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_is_reviewing],
        'run': handlers.mark_order_valid,
        'mutex': [],
        'target_list': ['mark_order_picking', 'mark_order_invalid'],
    },
    'mark_order_invalid': {
        'name_cn': '订单审核不通过',
        'note': '审核完订单清单中的药品资质，存在问题时，点击【审核不通过】',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_is_reviewing],
        'run': handlers.mark_order_invalid,
        'mutex': [],
        'target_list': ['mark_order_refunding', 'mark_order_valid'],
    },
    'mark_order_picking': {
        'name_cn': '订单拣配',
        'note': '检查订单清单中的药品库存，交易状态自动转入拣配中',
        'transit_type': Task.AUTO_TRANSIT,
        'condition_list': [conditions.order_can_pick],
        'run': handlers.mark_order_picking,
        'mutex': [],
        'target_list': ['mark_order_shipping'],
    },
    'close_order': {
        'name_cn': '订单关闭',
        'note': '检查订单清单中的药品库存缺货时，或者订单审核不通过时，或者订单超时未付款时，点击【订单关闭】',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_can_close],
        'run': handlers.close_order,
        'mutex': [],
        'target_list': [],
    },
    'mark_order_shipping': {
        'name_cn': '标记发货',
        'note': '拣配完药品，并装车发货后，点击【已发货】',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_can_ship],
        'run': handlers.mark_order_shipping,
        'mutex': [],
        'target_list': ['mark_order_received'],
    },
    'mark_order_received': {
        'name_cn': '确认收货',
        'note': '药品送达指定地址后，买家点击【确认收货】',
        'transit_type': Task.MANUAL_TRANSIT,
        'condition_list': [conditions.order_can_receive],
        'run': handlers.mark_order_received,
        'mutex': [],
        'target_list': [],
    },
}
